Traceback (most recent call last):
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/site-packages/nbclient/client.py", line 1087, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/asyncio/base_events.py", line 608, in run_until_complete
    return future.result()
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/site-packages/nbclient/client.py", line 540, in async_execute
    await self.async_execute_cell(
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/site-packages/nbclient/client.py", line 832, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/johannes/opt/anaconda3/envs/books/lib/python3.8/site-packages/nbclient/client.py", line 740, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply['content'])
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
im1="../pics/empire.jpg"
im2="../pics/blobs.png"
im3="../pics/gantrycrane.png"
im4="../pics/a4weiss.jpg"
image = img_as_float(data.imread(im4,as_grey=True))
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-2-d1f1d529b1d4>[0m in [0;36m<module>[0;34m[0m
[1;32m      3[0m [0mim3[0m[0;34m=[0m[0;34m"../pics/gantrycrane.png"[0m[0;34m[0m[0;34m[0m[0m
[1;32m      4[0m [0mim4[0m[0;34m=[0m[0;34m"../pics/a4weiss.jpg"[0m[0;34m[0m[0;34m[0m[0m
[0;32m----> 5[0;31m [0mimage[0m [0;34m=[0m [0mimg_as_float[0m[0;34m([0m[0mdata[0m[0;34m.[0m[0mimread[0m[0;34m([0m[0mim4[0m[0;34m,[0m[0mas_grey[0m[0;34m=[0m[0;32mTrue[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: module 'skimage.data' has no attribute 'imread'
AttributeError: module 'skimage.data' has no attribute 'imread'

